-- ============================================
-- Recreate public schema objects (based on current snapshot)
-- Review and modify before executing in production.
-- This script uses IF NOT EXISTS where possible.
-- ============================================

-- OPTIONAL: uncomment to drop certain objects before recreating (destructive)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.create_full_booking_transaction(integer,uuid,timestamp without time zone,text) CASCADE;
DROP FUNCTION IF EXISTS public.create_full_booking_transaction(uuid,uuid,timestamp without time zone,text) CASCADE;
DROP FUNCTION IF EXISTS public.create_full_booking_transaction(uuid,uuid,timestamp without time zone,text,uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_full_booking_transaction(uuid,uuid,timestamp without time zone,text,uuid,uuid) CASCADE;
DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.estimates CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.ping CASCADE;
DROP TABLE IF EXISTS public.properties CASCADE;
DROP TABLE IF EXISTS public.subscriptions CASCADE;
DROP TABLE IF EXISTS public.token_blocklist CASCADE;
DROP TABLE IF EXISTS public.user_properties CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.organizations CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.service_status CASCADE;
DROP TYPE IF EXISTS public.payment_status CASCADE;
DROP TYPE IF EXISTS public.estimate_status CASCADE;
DROP TYPE IF EXISTS public.maintenance_frequency CASCADE;
DROP TYPE IF EXISTS public.status CASCADE;
-- ============================================

-- 1) Create enum / user-defined types (if missing)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE public.user_role AS ENUM ('admin','user','provider');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'service_status') THEN
    CREATE TYPE public.service_status AS ENUM ('completed','scheduled','canceled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
    CREATE TYPE public.payment_status AS ENUM ('paid','canceled','pending');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estimate_status') THEN
    CREATE TYPE public.estimate_status AS ENUM ('accepted','rejected','pending');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'maintenance_frequency') THEN
    CREATE TYPE public.maintenance_frequency AS ENUM ('weekly','biweekly','monthly');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status') THEN
    CREATE TYPE public.status AS ENUM ('active','canceled','pending');
  END IF;
END$$;


-- 2) Create tables

-- organizations (multi-tenant root entity)
CREATE TABLE IF NOT EXISTS public.organizations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  domain text UNIQUE,
  logo_url text,
  primary_color text DEFAULT '#22c55e',
  primary_color_dark text DEFAULT '#14532d',
  background_color text DEFAULT '#f0fdf4',
  headline text DEFAULT 'mow delivered, just like that',
  tagline text,
  footer_text text,
  stripe_account_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_organizations_domain ON public.organizations(domain);
CREATE INDEX IF NOT EXISTS idx_organizations_slug ON public.organizations(slug);

-- users
CREATE TABLE IF NOT EXISTS public.users (
  -- According to refreshed snapshot: id is uuid (unique) and used as primary key
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email text UNIQUE,
  phone text UNIQUE,
  role public.user_role DEFAULT 'user'::public.user_role,
  password character varying DEFAULT 'test',
  first_name text,
  last_name text,
  source text DEFAULT 'mowzaic.com',
  stripe_id text,
  promo_opt boolean DEFAULT false,
  org_id uuid,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

-- properties
CREATE TABLE IF NOT EXISTS public.properties (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  city text,
  state text,
  postal text,
  address text,
  coordinates point,
  codes jsonb DEFAULT '[]'::jsonb,
  has_pets boolean DEFAULT false,
  org_id uuid,
  CONSTRAINT properties_pkey PRIMARY KEY (id)
);

-- messages
CREATE TABLE IF NOT EXISTS public.messages (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid,
  message text CHECK (length(message) <= 500),
  created_at timestamp DEFAULT now(),
  property_id uuid,
  org_id uuid,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- ping
CREATE TABLE IF NOT EXISTS public.ping (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  count integer DEFAULT 0,
  CONSTRAINT ping_pkey PRIMARY KEY (id)
);

-- estimates
CREATE TABLE IF NOT EXISTS public.estimates (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  price_cents integer DEFAULT 3500,
  accepted public.estimate_status DEFAULT 'pending'::public.estimate_status,
  property_id uuid,
  released_at timestamptz,
  released boolean DEFAULT false,
  org_id uuid,
  CONSTRAINT estimates_pkey PRIMARY KEY (id)
);

-- subscriptions
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  estimate_id bigint,
  start_date timestamp,
  canceled_at timestamp,
  frequency public.maintenance_frequency DEFAULT 'weekly'::public.maintenance_frequency,
  status public.status DEFAULT 'pending'::public.status,
  property_id uuid,
  user_id uuid,
  stripe_subscription_id text,
  next_service_date timestamp,
  org_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

-- Unique index to prevent multiple active subscriptions per property
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_subscription_per_property 
ON public.subscriptions(property_id) 
WHERE status = 'active';

-- user_properties
CREATE TABLE IF NOT EXISTS public.user_properties (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  created_at timestamptz DEFAULT now(),
  user_id uuid,
  property_id uuid,
  deleted_at timestamptz,
  org_id uuid,
  CONSTRAINT user_properties_pkey PRIMARY KEY (id),
  CONSTRAINT unique_user_property UNIQUE(user_id, property_id)
);

-- token_blocklist
CREATE TABLE IF NOT EXISTS public.token_blocklist (
  id integer GENERATED ALWAYS AS IDENTITY,
  token text,
  created_at timestamp DEFAULT now(),
  CONSTRAINT token_blocklist_pkey PRIMARY KEY (id)
);

-- bookings
-- Note: snapshot shows booking.id as uuid and customer/provider ids as uuid
CREATE TABLE IF NOT EXISTS public.bookings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  customer_id uuid,
  date_of_service timestamp,
  date_booked timestamp DEFAULT CURRENT_TIMESTAMP,
  subscription_id bigint,
  service_status public.service_status DEFAULT 'scheduled'::public.service_status,
  payment_status public.payment_status DEFAULT 'pending'::public.payment_status,
  provider_id uuid,
  message_id integer,
  job_duration_minutes integer,
  issue_flag boolean DEFAULT false CHECK (issue_flag = ANY (ARRAY[true, false])),
  property_id uuid,
  payment_intent_id text,
  org_id uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id)
);

-- Unique index to prevent overlapping bookings on same property/date
CREATE UNIQUE INDEX IF NOT EXISTS unique_property_booking_date 
ON public.bookings(property_id, date_of_service) 
WHERE service_status != 'canceled';

-- events
CREATE TABLE IF NOT EXISTS public.events (
  id bigint GENERATED ALWAYS AS IDENTITY,
  event_type text,
  metadata jsonb,
  source text DEFAULT 'internal'::text,
  created_at timestamp DEFAULT now(),
  org_id uuid,
  CONSTRAINT events_pkey PRIMARY KEY (id)
);

-- keep-alive (if present)
CREATE TABLE IF NOT EXISTS public."keep-alive" (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text DEFAULT ''::text,
  random uuid DEFAULT gen_random_uuid(),
  CONSTRAINT keep_alive_pkey PRIMARY KEY (id)
);

-- 3) Recreate foreign keys (only if referencing objects exist)
-- bookings -> subscriptions
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id);

-- bookings.customer_id -> users.id
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id);

-- bookings.provider_id -> users.id
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.users(id);

-- bookings.message_id -> messages.id
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id);

-- bookings.property_id -> properties.id
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id);

-- estimates.property_id -> properties.id
ALTER TABLE IF EXISTS public.estimates
  ADD CONSTRAINT estimates_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id);

-- messages.property_id -> properties.id
ALTER TABLE IF EXISTS public.messages
  ADD CONSTRAINT messages_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id);

-- messages.user_id -> users.id
ALTER TABLE IF EXISTS public.messages
  ADD CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

-- subscriptions.estimate_id -> estimates.id
ALTER TABLE IF EXISTS public.subscriptions
  ADD CONSTRAINT subscriptions_estimate_id_fkey FOREIGN KEY (estimate_id) REFERENCES public.estimates(id);

-- subscriptions.user_id -> users.id (users.id is uuid in snapshot)
ALTER TABLE IF EXISTS public.subscriptions
  ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

-- subscriptions.property_id -> properties.id
ALTER TABLE IF EXISTS public.subscriptions
  ADD CONSTRAINT subscriptions_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id);

-- user_properties.property_id -> properties.id
ALTER TABLE IF EXISTS public.user_properties
  ADD CONSTRAINT user_properties_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id);

-- user_properties.user_id -> users.id
ALTER TABLE IF EXISTS public.user_properties
  ADD CONSTRAINT user_properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

-- org_id foreign keys
ALTER TABLE IF EXISTS public.users
  ADD CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.properties
  ADD CONSTRAINT properties_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.bookings
  ADD CONSTRAINT bookings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.estimates
  ADD CONSTRAINT estimates_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.subscriptions
  ADD CONSTRAINT subscriptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.messages
  ADD CONSTRAINT messages_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.user_properties
  ADD CONSTRAINT user_properties_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);
ALTER TABLE IF EXISTS public.events
  ADD CONSTRAINT events_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id);

-- 4) Indexes & unique constraints observed
-- users.email and users.phone already declared UNIQUE in table creation above.
-- users.id is PK (uuid) already set.

CREATE INDEX IF NOT EXISTS idx_users_id ON public.users(id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON public.users(phone);

CREATE INDEX IF NOT EXISTS idx_user_properties_user_id ON public.user_properties(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_id ON public.bookings(customer_id);

-- org_id indexes for multi-tenant queries
CREATE INDEX IF NOT EXISTS idx_users_org_id ON public.users(org_id);
CREATE INDEX IF NOT EXISTS idx_properties_org_id ON public.properties(org_id);
CREATE INDEX IF NOT EXISTS idx_bookings_org_id ON public.bookings(org_id);
CREATE INDEX IF NOT EXISTS idx_estimates_org_id ON public.estimates(org_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_org_id ON public.subscriptions(org_id);
CREATE INDEX IF NOT EXISTS idx_messages_org_id ON public.messages(org_id);
CREATE INDEX IF NOT EXISTS idx_user_properties_org_id ON public.user_properties(org_id);
CREATE INDEX IF NOT EXISTS idx_events_org_id ON public.events(org_id);

-- 5) Placeholder auth schema and example trigger/function
-- Create auth schema if missing
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
    CREATE SCHEMA IF NOT EXISTS auth;
  END IF;
END$$;

-- Minimal placeholder for auth.users if missing (ONLY for local/dev; remove if using Supabase auth)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'auth' AND table_name = 'users') THEN
    CREATE TABLE auth.users (
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      email text,
      created_at timestamptz DEFAULT now()
    );
  END IF;
END$$;

-- Example function to copy auth.users into public.users (adjust to your real implementation)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  _role public.user_role;
  _org_id uuid;
BEGIN
  -- Read role from user metadata if provided (e.g., provider registration)
  -- Default to 'user' if not specified or invalid
  BEGIN
    _role := (NEW.raw_user_meta_data->>'role')::public.user_role;
  EXCEPTION WHEN OTHERS THEN
    _role := 'user';
  END;

  IF _role IS NULL THEN
    _role := 'user';
  END IF;

  -- Read org_id from user metadata if provided (multi-tenant signup)
  BEGIN
    _org_id := (NEW.raw_user_meta_data->>'org_id')::uuid;
  EXCEPTION WHEN OTHERS THEN
    _org_id := NULL;
  END;

  -- If a new auth user is created, insert into public.users using same uuid
  INSERT INTO public.users (id, email, source, password, role, org_id)
  VALUES (NEW.id, NEW.email, 'auth', 'oauth', _role, _org_id)
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

-- Function: check_and_create_property
-- Checks if property exists, validates ownership, and creates/associates it with user
CREATE OR REPLACE FUNCTION public.check_and_create_property(
    _address text,
    _city text,
    _state text,
    _postal text,
    _has_pets boolean,
    _coordinates point,
    _codes jsonb,
    _org_id uuid DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    existing_property_record RECORD;
    property_record RECORD;
    user_id_from_jwt uuid;
    active_association_exists boolean;
BEGIN
    -- Get the authenticated user's ID from JWT
    user_id_from_jwt := auth.uid();

    IF user_id_from_jwt IS NULL THEN
        RAISE EXCEPTION 'User not authenticated';
    END IF;

    -- Check if property exists with same address/city/state/postal (scoped to org if provided)
    SELECT * INTO existing_property_record
    FROM public.properties
    WHERE address = _address
      AND city = _city
      AND state = _state
      AND postal = _postal
      AND (_org_id IS NULL OR org_id = _org_id)
    LIMIT 1;

    IF existing_property_record.id IS NOT NULL THEN
        -- Property exists, check for active association
        SELECT EXISTS(
            SELECT 1 FROM public.user_properties
            WHERE property_id = existing_property_record.id
              AND user_id = user_id_from_jwt
              AND deleted_at IS NULL
        ) INTO active_association_exists;

        IF active_association_exists THEN
            -- User already has active association, return property
            RETURN row_to_json(existing_property_record);
        ELSE
            -- Create new association
            INSERT INTO public.user_properties (property_id, user_id, deleted_at, org_id)
            VALUES (existing_property_record.id, user_id_from_jwt, NULL, _org_id);

            RETURN row_to_json(existing_property_record);
        END IF;
    ELSE
        -- Property doesn't exist, create it
        INSERT INTO public.properties (address, city, state, postal, has_pets, coordinates, codes, org_id)
        VALUES (_address, _city, _state, _postal, _has_pets, _coordinates, _codes, _org_id)
        RETURNING * INTO property_record;

        -- Create association
        INSERT INTO public.user_properties (property_id, user_id, deleted_at, org_id)
        VALUES (property_record.id, user_id_from_jwt, NULL, _org_id);

        RETURN row_to_json(property_record);
    END IF;
END;
$$;

-- Function: create_full_booking_transaction
-- Creates estimate, subscription, message, and booking atomically
-- p_provider_id is optional - set by frontend based on which company site the customer booked from
CREATE OR REPLACE FUNCTION public.create_full_booking_transaction(
    p_user_id uuid,
    p_property_id uuid,
    p_date_of_service timestamp,
    p_message text,
    p_provider_id uuid DEFAULT NULL,
    p_org_id uuid DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    new_estimate_id bigint;
    new_subscription_id bigint;
    new_message_id integer;
    new_booking_record RECORD;
BEGIN
    -- Validate user is authenticated
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'User not authenticated';
    END IF;

    -- Create estimate
    INSERT INTO public.estimates (property_id, price_cents, org_id)
    VALUES (p_property_id, NULL, p_org_id)
    RETURNING id INTO new_estimate_id;

    -- Create subscription
    INSERT INTO public.subscriptions (estimate_id, property_id, user_id, status, org_id)
    VALUES (new_estimate_id, p_property_id, p_user_id, 'pending', p_org_id)
    RETURNING id INTO new_subscription_id;

    -- Create message if provided
    IF p_message IS NOT NULL AND p_message != '' THEN
        INSERT INTO public.messages (user_id, property_id, message, org_id)
        VALUES (p_user_id, p_property_id, p_message, p_org_id)
        RETURNING id INTO new_message_id;
    END IF;

    -- Create booking
    INSERT INTO public.bookings (
        customer_id,
        property_id,
        date_of_service,
        subscription_id,
        message_id,
        service_status,
        payment_status,
        provider_id,
        org_id
    )
    VALUES (
        p_user_id,
        p_property_id,
        p_date_of_service,
        new_subscription_id,
        new_message_id,
        'scheduled',
        'pending',
        p_provider_id,
        p_org_id
    )
    RETURNING * INTO new_booking_record;

    RETURN row_to_json(new_booking_record);
END;
$$;

-- Create trigger on auth.users if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger t
    JOIN pg_class c ON t.tgrelid = c.oid
    WHERE t.tgname = 'on_auth_user_created'
  ) THEN
    CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();
  END IF;
END$$;

-- Revoke public execute on function as a safety precaution
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;

-- Grant execute permissions to authenticated users for booking functions
GRANT EXECUTE ON FUNCTION public.check_and_create_property TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_full_booking_transaction TO authenticated;

-- 6) Seed example row (optional)
-- Do not run this if you already have the user; left commented for safety
-- INSERT INTO public.users (id, email, phone, first_name, last_name, role, source, password, promo_opt)
-- VALUES (
--   '703770b5-0d15-4603-a84e-5a32f41f0c96'::uuid,
--   'munoz02.rm@gmail.com',
--   '1234567890',
--   'rodrigo',
--   'munoz',
--   'user',
--   'mowzaic.com',
--   'oauth',
--   true
-- )
-- ON CONFLICT (id) DO NOTHING;

-- 7) Seed default organization
INSERT INTO public.organizations (id, name, slug, domain, primary_color, primary_color_dark, background_color, headline, footer_text)
VALUES (
  '00000000-0000-0000-0000-000000000001'::uuid,
  'Mowzaic',
  'mowzaic',
  'mowzaic.com',
  '#22c55e',
  '#14532d',
  '#f0fdf4',
  'mow delivered, just like that',
  'Mowzaic'
)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- End of recreation script
-- ============================================
