import express from 'express';
import { validateToken } from './middleware.js';
import { 
  createSupabaseClientWithAuth,
  asyncHandler,
  ValidationError,
  AuthenticationError,
  DatabaseError
} from './utils.js';
import logger from './logger.js';

const router = express.Router();

/*
* Create estimate for property
* Note: This route is used by admins/service providers to create estimates
* CREATE TABLE public.estimates (
*   id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
*   created_at timestamp with time zone NOT NULL DEFAULT now(),
*   property_id uuid NOT NULL,
*   price_cents integer NULL DEFAULT 3500,
*   CONSTRAINT estimates_pkey PRIMARY KEY (id),
*   CONSTRAINT estimates_property_id_fkey FOREIGN KEY (property_id) REFERENCES properties(id) ON UPDATE CASCADE ON DELETE CASCADE
* );
*/
router.post("/create-estimate", validateToken, asyncHandler(async (req, res) => {
  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith('Bearer ')) {
    throw new AuthenticationError('Missing or malformed authorization header');
  }

  const jwt = authHeader.split(' ')[1];
  const client = createSupabaseClientWithAuth(jwt);
  const { propertyId, priceCents } = req.body;

  if (!propertyId || !priceCents) {
    throw new ValidationError('Missing required fields: propertyId and priceCents');
  }

  // TODO: Add authorization check to ensure only admins/providers can create estimates
  // if (req.user.role !== 'admin' && req.user.role !== 'provider') {
  //   throw new AuthenticationError('Unauthorized: Only admins and providers can create estimates');
  // }

  const { data, error } = await client
    .from('estimates')
    .insert({ property_id: propertyId, price_cents: priceCents })
    .select()
    .single();

  if (error) {
    throw new DatabaseError('Error creating estimate');
  }

  //TODO: Notify user that estimate has been created via Twilio
  logger.info(`Estimate created for property ID: ${propertyId} with price: ${priceCents}`);
  res.json(data);
}));

export default router;

